### PR TITLE
Option to cycle windows

### PR DESCRIPTION
**Pull request by bosyi**
add option to cycle windows using keybindings;
fix bug when option 'raise_first' was chosen and no one window of wanted application were opened;
add 3.18 support to readme file.

hello. this is my fist commit & pull request.
cycling seems to work good. it opens the most old/last_used window.

### CODE REVIEW

**Comment by bosyi** [comment]
for now there are minor problem: if cycle_windows enabled, option raise_first 'not in game'.

**Comment by franziskuskiefer** [comment]
thanks for the PR!

lgtm mainly
the raise first works for me though even if I have cycle_windows enabled as well.

**Comment by franziskuskiefer** [comment]
Ah, now I see what you mean. Well, I'd say add some text (in the pres) to it that cycling windows implies raise first.

**Comment by bosyi** [comment]
I added warnings to both Cycle Windows and Raise First options tooltips.

**Comment by bosyi** [comment]
Also i do not know do i need change gschemas.xml and recompile it? For me tooltips were updated just by editing prefs.js.

**Pull request merged**
